# Generated by Django 4.1.5 on 2023-04-12 19:07

import ad.custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_company_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='Приоритетность кампании')),
                ('type', models.TextField(max_length=255, verbose_name='Тип и подтип кампании')),
                ('week_day', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресение')], max_length=150, null=True)),
                ('on_holiday', models.BooleanField(default=True, verbose_name='Показывать в праздничные дни')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала кампании')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения кампании')),
                ('key_word', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Список ключевых фраз')),
                ('minus_word', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Список минус фраз')),
                ('forbidden_site', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Список запрещенных для показа сайтов (url адреса через пробел)')),
                ('show_gender', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('Л', 'Любой')], max_length=150, null=True)),
                ('show_age', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('1', 'Младше 18'), ('2', '18 - 24'), ('3', '25 - 34'), ('4', '35 - 44'), ('5', '45 - 54'), ('6', 'Старше 54')], max_length=150, null=True)),
                ('regions', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('01', 'Республика Адыгея (Адыгея)'), ('02', 'Республика Башкортостан'), ('03', 'Республика Бурятия'), ('04', 'Республика Алтай'), ('05', 'Республика Дагестан'), ('06', 'Республика Ингушетия'), ('07', 'Кабардино-Балкарская Республика'), ('08', 'Республика Калмыкия'), ('09', 'Карачаево-Черкесская Республика'), ('10', 'Республика Карелия'), ('11', 'Республика Коми'), ('12', 'Республика Марий Эл'), ('13', 'Республика Мордовия'), ('14', 'Республика Саха (Якутия)'), ('15', 'Республика Северная Осетия - Алания'), ('16', 'Республика Татарстан (Татарстан)'), ('17', 'Республика Тыва'), ('18', 'Удмуртская Республика'), ('19', 'Республика Хакасия'), ('20', 'Чеченская Республика'), ('21', 'Чувашская Республика - Чувашия'), ('22', 'Алтайский край'), ('23', 'Краснодарский край'), ('24', 'Красноярский край'), ('25', 'Приморский край'), ('26', 'Ставропольский край'), ('27', 'Хабаровский край'), ('28', 'Амурская область'), ('29', 'Архангельская область'), ('30', 'Астраханская область'), ('31', 'Белгородская область'), ('32', 'Брянская область'), ('33', 'Владимирская область'), ('34', 'Волгоградская область'), ('35', 'Вологодская область'), ('36', 'Воронежская область'), ('37', 'Ивановская область'), ('38', 'Иркутская область'), ('39', 'Калининградская область'), ('40', 'Калужская область'), ('41', 'Камчатский край'), ('42', 'Кемеровская область - Кузбасс'), ('43', 'Кировская область'), ('44', 'Костромская область'), ('45', 'Курганская область'), ('46', 'Курская область'), ('47', 'Ленинградская область'), ('48', 'Липецкая область'), ('49', 'Магаданская область'), ('50', 'Московская область'), ('51', 'Мурманская область'), ('52', 'Нижегородская область'), ('53', 'Новгородская область'), ('54', 'Новосибирская область'), ('55', 'Омская область'), ('56', 'Оренбургская область'), ('57', 'Орловская область'), ('58', 'Пензенская область'), ('59', 'Пермский край'), ('60', 'Псковская область'), ('61', 'Ростовская область'), ('62', 'Рязанская область'), ('63', 'Самарская область'), ('64', 'Саратовская область'), ('65', 'Сахалинская область'), ('66', 'Свердловская область'), ('67', 'Смоленская область'), ('68', 'Тамбовская область'), ('69', 'Тверская область'), ('70', 'Томская область'), ('71', 'Тульская область'), ('72', 'Тюменская область'), ('73', 'Ульяновская область'), ('74', 'Челябинская область'), ('75', 'Забайкальский край'), ('76', 'Ярославская область'), ('77', 'город федерального значения Москва'), ('78', 'город федерального значения Санкт-Петербург'), ('79', 'Еврейская автономная область'), ('83', 'Ненецкий автономный округ'), ('86', 'Ханты-Мансийский автономный округ - Югра'), ('87', 'Чукотский автономный округ'), ('89', 'Ямало-Ненецкий автономный округ'), ('90', 'Запорожская область'), ('91', 'Республика Крым'), ('92', 'город федерального значения Севастополь'), ('93', 'Донецкая Народная Республика'), ('94', 'Луганская Народная Республика'), ('95', 'Херсонская область'), ('99', 'Иные территории, включая город и космодром Байконур')], max_length=150, null=True)),
                ('advanced_targeting', models.BooleanField(default=True, verbose_name='Расширенный географический таргетинг')),
                ('category_and_subcategory', models.TextField(default='', max_length=32768, verbose_name='Список категорий и подкатегорий')),
                ('target_actions', models.TextField(default='', max_length=32768, verbose_name='Список целевых действий')),
                ('counter_n', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер подключенного счетчика')),
                ('weekly_budget', models.IntegerField(verbose_name='Число недельного бюджета')),
                ('balance', models.IntegerField(default=0, verbose_name='Число денег на балансе')),
                ('gender_pr', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('Л', 'Любой')], max_length=150, null=True)),
                ('age_pr', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('1', 'Младше 18'), ('2', '18 - 24'), ('3', '25 - 34'), ('4', '35 - 44'), ('5', '45 - 54'), ('6', 'Старше 54')], max_length=150, null=True)),
                ('device_pr', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('Desktop', 'Десктопы'), ('Smartphone', 'Смартфоны'), ('Tablet', 'Планшеты')], max_length=150, null=True)),
                ('os_pr', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('1', 'Android'), ('2', 'CentOS'), ('3', 'Chrome OS'), ('4', 'Free BSD'), ('5', 'iOS'), ('6', 'Windows'), ('7', 'macOS'), ('8', 'Solaris'), ('9', 'Ubuntu'), ('10', 'Linux')], max_length=150, null=True)),
                ('solvency_pr', ad.custom.fields.SeparatedValuesField(blank=True, choices=[('1', '1%'), ('2', '2 - 5%'), ('3', '6 - 10%')], max_length=150, null=True)),
                ('link_to_ad', models.CharField(max_length=255, verbose_name='Ссылка на сайт рекламодателя')),
                ('header_list', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Список вариантов заголовков')),
                ('description_list', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Список вариантов описаний')),
                ('img_link', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Список вариантов изображений (url через пробел)')),
                ('product_link', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Список ссылок на товар (url через пробел)')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
        migrations.CreateModel(
            name='ad_company_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Рекламная кампания (Товарная)',
                'verbose_name_plural': 'Рекламные кампании (Товарная)',
            },
        ),
        migrations.CreateModel(
            name='ad_company_Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Рекламная кампания (Трафик)',
                'verbose_name_plural': 'Рекламные кампании (Трафик)',
            },
        ),
    ]
