# Generated by Django 4.1.5 on 2023-05-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_users', '0003_remove_user_last_name_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Объект рефера'),
        ),
    ]
